### ISSUE TITLE
missing constructor arguments

### ISSUE THREAD

**Issue by cryptitalk** [bnb-chain/greenfield-python-sdk#56]
in here: https://github.com/bnb-chain/greenfield-python-sdk/blob/main/examples/basic_storage.py#L51

missing `network_configuration`

**Comment by cryptitalk** [comment]
also missing `is_serial_compute_mode` here: https://github.com/bnb-chain/greenfield-python-sdk/blob/main/examples/basic_storage.py#L95

**Comment by alplabin** [comment]
Thanks for noticing it. The two issues you mentioned have been resolved in version 0.6.1, which has been recently released: https://github.com/bnb-chain/greenfield-python-sdk/releases/tag/v0.6.1
